services:
  php-apache:
    build: .
    container_name: php-apache
    environment:
      DB_HOST: db
      DB_NAME: viteetgourmand
      DB_USER: user
      DB_PASSWORD: costaud&
    depends_on:
      - db
    labels:
    - traefik.enable=true
    - traefik.http.routers.app.rule=Host(`mon-ecf-veg.pro`) || Host(`www.mon-ecf-veg.pro`)
    - traefik.http.routers.app.entrypoints=websecure
    - traefik.http.routers.app.tls.certresolver=letsencrypt
    - traefik.http.services.app.loadbalancer.server.port=80
    networks:
    - traefik-proxy
    - default

  db:
    image: mysql:8.0
    container_name: mydb
    environment:
      MYSQL_ROOT_PASSWORD: costaud&
      MYSQL_DATABASE: viteetgourmand
      MYSQL_USER: user
      MYSQL_PASSWORD: costaud&
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - default
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: costaud&
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma.rule=Host(`pma.mon-ecf-veg.pro`)
      - traefik.http.routers.pma.entrypoints=websecure
      - traefik.http.routers.pma.tls.certresolver=letsencrypt
      - traefik.http.services.pma.loadbalancer.server.port=80
    networks:
    - traefik-proxy
    - default
volumes:
  dbdata:
